#@TYPE: Machine
#@NAME: raptor machine
#@DESCRIPTION: Machine configuration for running Raptor

SOC_FAMILY = "r8a779g0"

DEFAULTTUNE ?= "cortexa76"
require conf/machine/include/arm/armv8-2a/tune-cortexa76.inc
require conf/machine/include/rcar-common.inc

WKS_FILE = "image-v4x.wks"

# Raptor kernel configure
RTX_KERNEL_URL = "git://git@github.com/RetronixTechInc/rcar-gen4-kernel.git;protocol=ssh"
RTX_KERNEL_BRANCH = "v4h-raptor/v5.10.235/rcar-5.2.2.rc2"
RTX_KERNEL_REV = "${AUTOREV}"
RTX_KERNEL_EXTRA_CONFIGS = ""

# Wait for kernel porting
#KERNEL_DEVICETREE = " \
#	renesas/r8a779g0-raptor.dtb \
#	renesas/r8a779g0-raptor-overlay-pcie1x4.dtb \
#	renesas/r8a779g0-raptor-overlay-dsi0-7.dtb \
#	renesas/r8a779g0-raptor-overlay-dsi0-10.dtb \
#	renesas/r8a779g0-raptor-overlay-dsi1-7.dtb \
#	renesas/r8a779g0-raptor-overlay-dsi1-10.dtb \
#"

KERNEL_DEVICETREE = " \
    renesas/r8a779g0-whitehawk.dtb \
    renesas/r8a779g0-whitehawk-native.dtb \
    renesas/r8a779g0-whitehawk-sound.dtb \
    renesas/r8a779g3-white-hawk.dtb \
    renesas/r8a779g3-whitehawk-native.dtb \
    renesas/r8a779g3-whitehawk-sound.dtb \
    renesas/r8a779g4-white-hawk.dtb \
    renesas/r8a779g4-whitehawk-native.dtb \
    renesas/r8a779g4-whitehawk-sound.dtb \
    renesas/r8a779g5-white-hawk.dtb \
    renesas/r8a779g5-whitehawk-native.dtb \
    renesas/r8a779g5-whitehawk-sound.dtb \
    renesas/r8a779g0-whitehawk-rgid.dtb \
    renesas/r8a779g0-whitehawk-sound-rgid.dtb \
    renesas/r8a779g3-white-hawk-rgid.dtb \
    renesas/r8a779g3-whitehawk-sound-rgid.dtb \
    renesas/r8a779g4-white-hawk-rgid.dtb \
    renesas/r8a779g4-whitehawk-sound-rgid.dtb \
    renesas/r8a779g5-white-hawk-rgid.dtb \
    renesas/r8a779g5-whitehawk-sound-rgid.dtb \
    renesas/r8a779g0-whitehawk-du-native.dtb \
    renesas/r8a779g3-whitehawk-du-native.dtb \
    renesas/r8a779g4-whitehawk-du-native.dtb \
    renesas/r8a779g5-whitehawk-du-native.dtb \
"

# Raptor u-boot configure
# Wait for U-boot porting
#UBOOT_CONFIG ??= "raptor"
#UBOOT_CONFIG[raptor] = "r8a779g0_raptor_defconfig"
UBOOT_CONFIG ??= "whitehawk"
UBOOT_CONFIG[whitehawk] = "r8a779g0_whitehawk_defconfig"

RTX_UBOOT_URL = "git://git@github.com/RetronixTechInc/rcar-uboot.git;protocol=https"
RTX_UBOOT_BRANCH = "v4h-raptor/v2022.01/rcar-6.0.0.rc13"
RTX_UBOOT_REV = "${AUTOREV}"

# Set Image & SDK name for Raptor
IMAGE_NAME = "${IMAGE_BASENAME}-v4h${IMAGE_VERSION_SUFFIX}"
IMAGE_LINK_NAME = "${IMAGE_BASENAME}-v4h"
SDK_NAME_r8a779g0 = "${DISTRO}-${TCLIBC}-${SDKMACHINE}-${IMAGE_BASENAME}-${TUNE_PKGARCH}-v4h"

# machine specific package
IMAGE_INSTALL:raptor += " \
	linux-firmware-renesas \
"

PREFERRED_PROVIDER_virtual/egl = "${@bb.utils.contains('MACHINE_FEATURES', 'gsx', 'gles-user-module', '', d)}"
PREFERRED_PROVIDER_virtual/libgles2 = "${@bb.utils.contains('MACHINE_FEATURES', 'gsx', 'gles-user-module', '', d)}"
BBMASK += "${@bb.utils.contains('MACHINE_FEATURES', 'gsx', '', 'meta-renesas/meta-rcar-adas/recipes-graphics/mesa/ \
                                meta-renesas/meta-rcar-adas/recipes-kernel/kernel-module-gles/ \
                                meta-renesas/meta-rcar-adas/recipes-graphics/gles-user-module/', d)}"
